### ISSUE TITLE
if the filepath of my proc include "logrus",  the output of filename will be worry

### ISSUE THREAD

**Issue by spiderpoison** [onrik/logrus#5]
for example
i have a proc in path "logrus_test"
like this:

func main() {
	log.AddHook(filename.NewHook())

	log.SetLevel(log.DebugLevel)

	log.Debug("Useful debugging information.")
}

the output like this:

time="2018-08-01T19:37:01+08:00" level=debug msg="Useful debugging information." source="runtime/proc.go:195"

**Comment by onrik** [comment]
Fixed.

**Comment by shutcode** [comment]
if my project  named "logrus"(like go/src/test/logrus), it's still wrong. It is not enough: `SkipPrefixes: []string{"logrus/", "logrus@"},`

**Comment by onrik** [comment]
@shutcode You can customise SkipPrefixes.
```go
hook := filename.NewHook()
hook.SkipPrefixes = []string{"Custom", "prefixes"}
```
